# Practical_6: Numpy

### Exercise 1:
Create a NumPy array of integers from 1 to 10.

In [1]:
import numpy as np

In [3]:
a = np.arange(1,11) 
print(a)


[ 1  2  3  4  5  6  7  8  9 10]


### Exercise 2:
Create a 3x3 NumPy array filled with zeros.

In [28]:
a = np.zeros((3,3), dtype=np.int16)
a

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int16)

### Exercise 3:
Create a NumPy array of 10 evenly spaced numbers between 0 and 5.

In [8]:
a = np.linspace(0,5,10)
a

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [29]:
a = np.linspace(0,5,10, endpoint=False)
a

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

### Exercise 4:
Create a 5x5 identity matrix using NumPy.

In [9]:
a = np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [30]:
a = np.eye(5,6)
a

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.]])

### Exercise 5:
Create a 4x4 matrix with random values between 0 and 1.

In [11]:
from math import *
a = np.random.random((4,4))
a

array([[0.93598624, 0.72800368, 0.93856099, 0.74381336],
       [0.97312032, 0.96275656, 0.46255928, 0.1084313 ],
       [0.66956404, 0.49373381, 0.6588788 , 0.74187638],
       [0.22799509, 0.8251452 , 0.65059168, 0.81868551]])

In [32]:
a = np.random.rand(4,4)
a

array([[0.53305092, 0.74803555, 0.62561823, 0.34882657],
       [0.17463511, 0.17080249, 0.19882696, 0.16985489],
       [0.26764504, 0.89487462, 0.49588107, 0.75216537],
       [0.02834022, 0.32051374, 0.11106397, 0.01498346]])

In [52]:
np.random.seed(10)
a = np.random.rand(4,4)
a

array([[0.77132064, 0.02075195, 0.63364823, 0.74880388],
       [0.49850701, 0.22479665, 0.19806286, 0.76053071],
       [0.16911084, 0.08833981, 0.68535982, 0.95339335],
       [0.00394827, 0.51219226, 0.81262096, 0.61252607]])

In [63]:
np.random.seed(0)
a = np.random.rand(4,4)
a

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

### Exercise 6:
Find the shape of a NumPy array.

In [14]:
a.shape

(4, 4)

### Exercise 7:
Reshape a 1D NumPy array of 16 elements into a 4x4 matrix.

In [15]:
a = np.arange(1, 17).reshape((4, 4))
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

### Exercise 8:
Find the data type of the elements in a NumPy array.

In [18]:
a.dtype

dtype('int64')

### Exercise 9:
Create a NumPy array of integers from 1 to 100 and find all even numbers in the array.

In [26]:
a = np.arange(2, 102, 2) 
a

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

### Exercise 10:
mGenerate a 6x6 matrix of random integers between 10 and 50.

In [23]:
a = np.random.randint(10,50, size=(6,6))
a

array([[29, 11, 12, 42, 25, 24],
       [37, 10, 27, 26, 15, 44],
       [43, 14, 43, 15, 20, 26],
       [44, 36, 31, 42, 44, 33],
       [24, 45, 12, 49, 16, 10],
       [38, 11, 19, 47, 15, 33]])

In [64]:
a = np.random.randint(10,50,(6,6))
a

array([[26, 15, 25, 10, 28, 45],
       [34, 39, 29, 29, 24, 49],
       [42, 11, 19, 42, 41, 20],
       [33, 45, 21, 38, 44, 10],
       [10, 46, 15, 48, 27, 25],
       [14, 41, 11, 11, 49, 45]])

### Exercise 11:
Slice a 2D NumPy array to extract a submatrix.

In [66]:
b = a[:2, 1:3]
b

array([[15, 25],
       [39, 29]])

### Exercise 12:
Calculate the sum of all elements in a NumPy array.

In [68]:
np.sum(a)

1061


### Exercise 13:
Calculate the mean, median, and standard deviation of a NumPy array.


In [72]:
print(np.mean(a))
print(np.median(a))
print(np.std(a))

29.47222222222222
28.5
13.198245066655874


### Exercise 14:
Find the maximum and minimum values in a NumPy array.

In [73]:
print(np.min(a))
print(np.max(a))

10
49


### Exercise 15:
Create a NumPy array of 20 random integers and find the index of the maximum value.

In [94]:
b = np.random.randint(10,50, size = 20)
print(b)
#c = int(np.where(np.max(b)[0]))
print(np.where(b==np.max(b))[0])

print(np.argmax(b))
print(np.argmin(b))

[43 47 33 37 39 43 32 17 19 10 29 46 27 30 13 11 30 46 14 26]
[1]
1
9



### Exercise 16:
Create a NumPy array and reverse its elements.

In [84]:
b = np.random.randint(10,50, size = 20)
print(b)
print(np.flip(b))

[44 15 26 18 11 27 45 37 46 35 13 49 45 40 39 43 28 27 39 30]
[30 39 27 28 43 39 40 45 49 13 35 46 37 45 27 11 18 26 15 44]


### Exercise 17:
Create a 3x3 matrix and multiply it element-wise by another 3x3 matrix.

In [86]:
a = np.random.randint(10,50, size=(3,3))
print(a)
b = np.random.randint(1,10, size=(3,3))
print(b)
print(a * b)

[[42 37 19]
 [38 27 10]
 [32 26 46]]
[[9 5 4]
 [4 9 9]
 [8 1 4]]
[[378 185  76]
 [152 243  90]
 [256  26 184]]


### Exercise 18:
Create a diagonal matrix from a given 1D array.

In [88]:
a = np.arange(12)
print(a)
print(np.diag(a))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  1  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  2  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  3  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  4  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  5  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  6  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  7  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  8  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  9  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 10  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 11]]


### Exercise 19:
Perform matrix multiplication on two 2D NumPy arrays.

In [90]:
a = np.random.randint(10,50, size=(3,3))
print(a)
b = np.random.randint(1,10, size=(3,3))
print(b)
print(a.dot(b))
a@b

[[18 23 15]
 [10 18 25]
 [25 21 14]]
[[8 5 2]
 [4 4 3]
 [6 3 4]]
[[326 227 165]
 [302 197 174]
 [368 251 169]]


array([[326, 227, 165],
       [302, 197, 174],
       [368, 251, 169]])

### Exercise 20:
Flatten a 2D NumPy array into a 1D array.

In [91]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr) 

[1 2 3 4 5 6]


### Exercise 21:
Stack two NumPy arrays vertically.

In [92]:
a = np.random.randint(10,50, size=(3,3))
print(a)
b = np.random.randint(1,10, size=(3,3))
print(b)
print(np.vstack((a,b)))


[[40 28 33]
 [11 16 40]
 [26 36 45]]
[[2 7 7]
 [8 9 9]
 [8 1 9]]
[[40 28 33]
 [11 16 40]
 [26 36 45]
 [ 2  7  7]
 [ 8  9  9]
 [ 8  1  9]]


### Exercise 22:
Stack two NumPy arrays horizontally.

In [95]:
a = np.random.randint(10,50, size=(3,3))
print(a)
b = np.random.randint(1,10, size=(3,3))
print(b)
print(np.hstack((a,b)))


[[20 40 37]
 [41 30 16]
 [19 37 45]]
[[4 3 2]
 [3 2 4]
 [5 2 2]]
[[20 40 37  4  3  2]
 [41 30 16  3  2  4]
 [19 37 45  5  2  2]]



### Exercise 23:
Split a NumPy array into multiple sub-arrays.

In [100]:
c = np.hstack((a,b))
print(c)
np.split(c,3)

[[20 40 37  4  3  2]
 [41 30 16  3  2  4]
 [19 37 45  5  2  2]]


[array([[20, 40, 37,  4,  3,  2]]),
 array([[41, 30, 16,  3,  2,  4]]),
 array([[19, 37, 45,  5,  2,  2]])]

### Exercise 24:
Generate a random NumPy array and round each element to two decimal places.

In [115]:
d = c/1.5
d

array([[13.33333333, 26.66666667, 24.66666667,  2.66666667,  2.        ,
         1.33333333],
       [27.33333333, 20.        , 10.66666667,  2.        ,  1.33333333,
         2.66666667],
       [12.66666667, 24.66666667, 30.        ,  3.33333333,  1.33333333,
         1.33333333]])

In [116]:
np.around(d, decimals=2, out=None)

array([[13.33, 26.67, 24.67,  2.67,  2.  ,  1.33],
       [27.33, 20.  , 10.67,  2.  ,  1.33,  2.67],
       [12.67, 24.67, 30.  ,  3.33,  1.33,  1.33]])

In [113]:
help(np.around)

Help on function around in module numpy:

around(a, decimals=0, out=None)
    Evenly round to the given number of decimals.
    
    Parameters
    ----------
    a : array_like
        Input data.
    decimals : int, optional
        Number of decimal places to round to (default: 0).  If
        decimals is negative, it specifies the number of positions to
        the left of the decimal point.
    out : ndarray, optional
        Alternative output array in which to place the result. It must have
        the same shape as the expected output, but the type of the output
        values will be cast if necessary. See `ufuncs-output-type` for more
        details.
    
    Returns
    -------
    rounded_array : ndarray
        An array of the same type as `a`, containing the rounded values.
        Unless `out` was specified, a new array is created.  A reference to
        the result is returned.
    
        The real and imaginary parts of complex numbers are rounded
        separately.

### Exercise 25:
Find the unique elements of a NumPy array.

In [101]:
c = np.hstack((a,b))
print(c)
np.unique(c)

[[20 40 37  4  3  2]
 [41 30 16  3  2  4]
 [19 37 45  5  2  2]]


array([ 2,  3,  4,  5, 16, 19, 20, 30, 37, 40, 41, 45])

### Exercise 26:
Replace all elements in a NumPy array that are less than a specific value with that value.

In [106]:
b = np.random.randint(10,50, size = 20)
print(b)
b[b > 20] = 20


b

[10 49 34 46 45 15 16 13 44 43 38 14 36 42 19 15 43 17 40 18]


array([10, 20, 20, 20, 20, 15, 16, 13, 20, 20, 20, 14, 20, 20, 19, 15, 20,
       17, 20, 18])

### Exercise 27:
Find the cumulative sum of the elements in a NumPy array.

In [107]:
np.sum(b)

357


### Exercise 28:
Create a NumPy array and find the number of non-zero elements in it.

In [108]:
np.count_nonzero(b)

20

### Exercise 29:
Create a NumPy array of random integers and sort it in ascending order.

In [109]:
np.sort(b)

array([10, 13, 14, 15, 15, 16, 17, 18, 19, 20, 20, 20, 20, 20, 20, 20, 20,
       20, 20, 20])

### Exercise 30:
Find the row-wise and column-wise sum of a 3x3 matrix.

In [110]:
b = np.random.randint(10,50, size = (3,3))
print(b)
print(np.sum(b, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(b, axis=1))  #

[[30 17 13]
 [31 37 13]
 [48 30 17]]
[109  84  43]
[60 81 95]



### Exercise 31:
Generate a 2D NumPy array with random values and normalize it (scale the values between 0 and 1).


In [121]:
help(np.linalg.norm)

Help on function norm in module numpy.linalg:

norm(x, ord=None, axis=None, keepdims=False)
    Matrix or vector norm.
    
    This function is able to return one of eight different matrix norms,
    or one of an infinite number of vector norms (described below), depending
    on the value of the ``ord`` parameter.
    
    Parameters
    ----------
    x : array_like
        Input array.  If `axis` is None, `x` must be 1-D or 2-D, unless `ord`
        is None. If both `axis` and `ord` are None, the 2-norm of
        ``x.ravel`` will be returned.
    ord : {non-zero int, inf, -inf, 'fro', 'nuc'}, optional
        Order of the norm (see table under ``Notes``). inf means numpy's
        `inf` object. The default is None.
    axis : {None, int, 2-tuple of ints}, optional.
        If `axis` is an integer, it specifies the axis of `x` along which to
        compute the vector norms.  If `axis` is a 2-tuple, it specifies the
        axes that hold 2-D matrices, and the matrix norms of these

In [122]:
b = np.random.randint(10,50, size = (3,3))
print(b)
print(b/np.linalg.norm(b))  


[[23 40 33]
 [44 45 19]
 [36 36 32]]
[[0.21775773 0.3787091  0.31243501]
 [0.41658001 0.42604774 0.17988682]
 [0.34083819 0.34083819 0.30296728]]


### Exercise 32:
Create two NumPy arrays and find the dot product.

In [119]:
a = np.random.randint(10,50, size=(3,3))
print(a)
b = np.random.randint(1,10, size=(3,3))
print(b)
print(a.dot(b))


[[31 47 38]
 [18 10 48]
 [35 20 44]]
[[8 1 4]
 [1 4 7]
 [2 3 5]]
[[371 333 643]
 [250 202 382]
 [388 247 500]]


### Exercise 34:
Create a 2D array and swap two rows.

In [125]:
a = np.random.randint(10,50, size=(5,5))
print(a)
a[[0, 2]] = a[[2, 0]]
a

[[22 25 44 36 48]
 [26 10 20 21 23]
 [17 40 16 40 25]
 [48 28 17 38 11]
 [12 38 24 47 37]]


array([[17, 40, 16, 40, 25],
       [26, 10, 20, 21, 23],
       [22, 25, 44, 36, 48],
       [48, 28, 17, 38, 11],
       [12, 38, 24, 47, 37]])

### Exercise 35:
Create a 1D NumPy array and convert it into a column vector.

In [8]:
a = np.random.randint(10,50, size=(5))
print(a)
np.transpose(a)

[42 26 46 37 21]


array([42, 26, 46, 37, 21])

### Exercise 36:
Find the determinant of a 3x3 matrix.

In [126]:
a = np.random.randint(10,50, size=(5,5))
print(a)
np.linalg.det(a)

[[46 41 39 39 43]
 [22 42 26 12 18]
 [20 36 37 11 10]
 [15 34 44 25 13]
 [47 29 34 16 30]]


626705.9999999987

### Exercise 37:
Find the eigenvalues and eigenvectors of a 2x2 matrix.

In [128]:
a = np.random.randint(10,50, size=(2,2))
print(a)
w,v = np.linalg.eig(a)
print('E-value:', w)
print('E-vector', v)


[[38 38]
 [48 47]]
E-value: [-0.44473192 85.44473192]
E-vector [[-0.70298116 -0.62513847]
 [ 0.71120848 -0.78051387]]


### Exercise 38:
Solve a system of linear equations using NumPy.

In [130]:
a = np.array([[1, 2], [3, 5]])

b = np.array([1, 2])

x = np.linalg.solve(a, b)

x



array([-1.,  1.])


### Exercise 39:
Add Gaussian noise to a NumPy array.

In [3]:
a = np.random.randint(10,50, size=(4,4))
print(a)
gaussian_noise = np.random.normal(np.mean(a), np.std(a), a.shape)
gaussian_noise+a


[[49 28 16 22]
 [24 45 38 42]
 [11 27 26 32]
 [35 40 24 27]]


array([[72.15785868, 62.23853378, 55.38850066, 35.16291332],
       [58.7938461 , 80.4919219 , 62.93630769, 63.52138298],
       [36.71720962, 61.37904774, 61.72510755, 54.61352688],
       [65.1603655 , 59.59781643, 60.08841785, 45.53376665]])

### Exercise 40:
Create a 4x4 matrix and extract the diagonal elements.


In [4]:
a = np.random.randint(10,50, size=(4,4))
print(a)
arr2 = np.diag(a)
arr2


[[40 23 12 12]
 [46 32 19 10]
 [22 26 38 27]
 [25 28 11 22]]


array([40, 32, 38, 22])